insert into categories values (1, 'Tavoli','Tavoli per cucina');
insert into products values(1,1,'TAVCUC001','Tavolo WOOD', 'Tavolo in legno bellissimo',5,'DISPONIBILE');
insert into customers values(1, 'Mario','Rossi','','mario.rossi@email.it','');
insert into orders values (1,1,1,current_date(),current_date(),'IN PREPARAZIONE','',1,null);
--insert into categories values (1, 'Tavoli','Tavoli per cucina');
insert into products values(2,1,'TAVCUC001','Tavolo MARBLE', 'Tavolo in marmo',5,'DISPONIBILE');
insert into customers values(2, 'Giulia','Verdi','','gverdi@email.it','');
insert into orders values (2,2,2,current_date(),current_date(),'DA PAGARE','',2,null);